services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: hobio_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hobio_network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 5
    
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: hobio_api
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__RabbitMq=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hobio_network

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: hobio_worker
    environment:
      - ConnectionStrings__RabbitMq=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - hobio_network

networks:
  hobio_network:
    driver: bridge