<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-hobio.worker-3e7e2817-4ef9-4418-bb2f-edbb190bea6e</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.5.7" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />

    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\shared\hobio.shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Program.cs">
        <ExcludeFromCodeCoverage />
      </Compile>
    </ItemGroup>

</Project>
