name: Build and Deploy (Cloud Run)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build for'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: read
  packages: write
  id-token: write

env:
  VPC_CONNECTOR_DEV: projects/hobio-nonprod/locations/us-east1/connectors/hobio-nonprod-vpc-ue1
  VPC_CONNECTOR_PROD: projects/hobio-prod/locations/us-east1/connectors/hobio-prod-vpc-ue1
  SECRET_NAME_DEV: rabbitmq-connection-string-dev
  SECRET_NAME_PROD: rabbitmq-connection-string-prod

jobs:
  build-api:  
    uses: nirojasmar/base-workflows/.github/workflows/docker-test-build.yml@v0.4.0
    with:
      image_name: hobio-${{ github.event.inputs.environment == 'prod' && 'prod' || 'nonprod' }}/hobio-${{ github.event.inputs.environment == 'prod' && 'prod' || 'nonprod' }}-repo-ue1/hobio-api
      environment: ${{ github.event.inputs.environment || 'dev'}} 
      dockerfile_path: api/Dockerfile
    secrets: inherit

  deploy-api:
    if: github.event_name != 'pull_request'
    needs: build-api
    uses: nirojasmar/base-workflows/.github/workflows/cloud-run-deploy.yml@feature/cloud-run-deploy
    with:
      image_name: ${{ needs.build-api.outputs.image_name }}
      environment: ${{ github.event.inputs.environment || 'dev'}} 
      service: hobio-api-${{ github.event.inputs.environment == 'prod' && 'prod' || 'nonprod' }}
      vpc_connector: ${{ github.event.inputs.environment == 'prod' && env.VPC_CONNECTOR_PROD || env.VPC_CONNECTOR_DEV }}
      secrets: ConnectionStrings__RabbitMQ=${{ github.event.inputs.environment == 'prod' && env.SECRET_NAME_PROD || env.SECRET_NAME_DEV }}:latest
    secrets: inherit

  build-worker:
    uses: nirojasmar/base-workflows/.github/workflows/docker-test-build.yml@v0.4.0
    with:
      image_name: hobio-${{ github.event.inputs.environment == 'prod' && 'prod' || 'nonprod' }}/hobio-${{ github.event.inputs.environment == 'prod' && 'prod' || 'nonprod' }}-repo-ue1/hobio-worker
      environment: ${{ github.event.inputs.environment || 'dev'}} 
      dockerfile_path: worker/Dockerfile
    secrets: inherit

  deploy-worker:
    if: github.event_name != 'pull_request'
    needs: build-worker
    uses: nirojasmar/base-workflows/.github/workflows/cloud-run-deploy.yml@feature/cloud-run-deploy
    with:
      image_name: ${{ needs.build-worker.outputs.image_name }}
      environment: ${{ github.event.inputs.environment || 'dev'}} 
      service: hobio-worker-${{ github.event.inputs.environment == 'prod' && 'prod' || 'nonprod' }}
      vpc_connector: ${{ github.event.inputs.environment == 'prod' && env.VPC_CONNECTOR_PROD || env.VPC_CONNECTOR_DEV }}
      secrets: ConnectionStrings__RabbitMQ=${{ github.event.inputs.environment == 'prod' && env.SECRET_NAME_PROD || env.SECRET_NAME_DEV }}:latest
    secrets: inherit
