name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to build for'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: read
  packages: write
  id-token: write

env:
  ENVIRONMENT: ${{ github.event.inputs.environment || 'dev'}}
  
jobs:
  build-api:
    uses: nirojasmar/base-workflows/.github/workflows/docker-test-build.yml@infra-workflows
    with:
      image_name: hobio-${{ env.ENVIRONMENT == 'prod' && 'prod' || 'nonprod' }}/hobio-${{ env.ENVIRONMENT == 'prod' && 'prod' || 'nonprod' }}-repo-ue1/hobio-api
      environment: ${{ env.ENVIRONMENT }} 
      registry_host: us-east1-docker.pkg.dev
      dockerfile_path: api/Dockerfile
    secrets: inherit

  build-worker:
    uses: nirojasmar/base-workflows/.github/workflows/docker-test-build.yml@infra-workflows
    with:
      image_name: hobio-${{ env.ENVIRONMENT == 'prod' && 'prod' || 'nonprod' }}/hobio-${{ env.ENVIRONMENT == 'prod' && 'prod' || 'nonprod' }}-repo-ue1/hobio-worker
      environment: ${{ env.ENVIRONMENT }}
      registry_host: us-east1-docker.pkg.dev
      dockerfile_path: worker/Dockerfile
    secrets: inherit
