name: Sonar Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    uses: nirojasmar/base-workflows/.github/workflows/sonar-scan.yml@feature/6-firestore-emulator
    with:
      project_key: "hobio"
      scanner_type: "dotnet"
      test_settings_path: "tests/coverlet.runsettings"
      enable_firestore_emulator: true
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORG: ${{ secrets.SONAR_ORG }}
 
